### ISSUE TITLE
Duplication caused by adding "mainSourceFile" to "sourceFiles"

### ISSUE THREAD

**Issue by jaypha** [D-Programming-Language/dub#452]
When updating to the latest version of Dub, I was forced to change the value for the "mainSourceFile" from "sample.d" to "src/sample.d". By adding it to "sourceFiles", a spurious "sample.d" was passed to the compiler in addition to "src/sample.d", causing the compiler to reject with a "cannot read sample.d" error.

**Comment by s-ludwig** [comment]
The behavior was changed intentionally, because it was often redundant to specify the main file once as "mainSourceFile" and once as "sourceFiles". In the described example, the `"mainSourceFile": "sample.d"` simply didn't have any effect, because that file doesn't exist - the new behavior now has the advantage of triggering an error in this case, so that the mistake gets more obvious.
