### ISSUE TITLE
Trigger manual update is not working

### ISSUE THREAD

**Issue by MrSmith33** [D-Programming-Language/dub#507]
It always looks like this:
![issue](https://cloud.githubusercontent.com/assets/1129910/6131935/13091610-b158-11e4-968b-58d971568ed4.png)

**Comment by s-ludwig** [comment]
Look like it just takes quite a while to process the queue. "Trigger manual update" just forcefully enqueues the package for an update, so when the half hourly check of all packages is already in progress, it still has to wait for that to complete. Unfortunately GitHub only allows about one request per second, so that checking all packages/branches/tags takes quite some time, even with aggressive caching.

See also https://github.com/D-Programming-Language/dub-registry/issues/92, https://github.com/D-Programming-Language/dub-registry/issues/91 and https://github.com/D-Programming-Language/dub-registry/issues/10

**Comment by MrSmith33** [comment]
Now it makes sense.

**Comment by s-ludwig** [comment]
I've now implemented a more detailed status message, so that it's now clear where in the queue a package currently is.
(Closing this issue)
