### ISSUE TITLE
Private registry

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#525]
May I use private packages not in the DUB registry, while still using versionned dependencies? It doesn't seem like path-based dependencies can do that.

**Comment by etcimon** [comment]
I think you'd have to install the dub registry on your server and change the URL in the source code.

**Comment by p0nce** [comment]
Well I'd really like something much simpler.

**Comment by etcimon** [comment]
In that case I would use a combination of shell script and a dub path to checkout the proper version.

The `preBuildCommands` will allow you to run shell scripts.

**Comment by p0nce** [comment]
I'm looking for something more builtin.

**Comment by s-ludwig** [comment]
You can always check out the dependencies locally and use add-path/add-local to register them. There is currently no mechanism to automatically check out different branches/tags, so that needs to be done manually (although usually you'd just stay on a single branch most of the time), but everything else should work as it's supposed to.

Using a non-default registry can be done by either using the `--registry=URL` switch, or by adding a `"registryUrls": ["http://..."]` field to `.dub/settings.json` (or `%AppData%\dub\settings.json` on Windows). But the registry currently only supports GitHub and BitBucket.

**Comment by p0nce** [comment]
I see. It would be great to have add-local/add-path work with versions and git tags though.

**Comment by s-ludwig** [comment]
If you have a branch checked out, it will look at the latest tag to determine the version. And of course if you have checked out a specific tag, that will be used, too.

**Comment by s-ludwig** [comment]
Maybe it would also make sense to let DUB call Git to automatically switch to different branches/tags, but that may just make things more complicated when there are for example local modifications.

**Comment by MartinNowak** [comment]
You can clone your local repo multiple times with different versions checked out.
This should do the trick.
```
git clone -b v0.2.0 myrepo myrepo-0.2.0
dub add-local myrepo-0.2.0
git clone -b v0.2.1 myrepo myrepo-0.2.1
dub add-local myrepo-0.2.1
```

**Comment by p0nce** [comment]
Looks reasonable.
