### ISSUE TITLE
win32-dmd: problem if binary name contains spaces

### ISSUE THREAD

**Issue by Extrawurst** [D-Programming-Language/dub#569]
on windows dub cannot build binaries that contain spaces in the name since it does not pass the output name in `"` to dmd. either warn on names with spaces or fix the cmd line parameter passing

**Comment by Positronic** [comment]
I want to bump this as well with more information.  I'm on Win 7 64-bit, so this is not limited to win32.
I'm not entirely sure what dub is doing because I've built this project in the past with the same %APPDATA% path (and my username has a space in it) and it worked.

I recently updated my dmd from 2.066.0 to 2.067.1 so perhaps it's dmd or my sc.ini, but I don't think it is.  I have been able to successfully build by forcing %APPDATA% to be something like C:\ProgramData\ which has no spaces.  But I can't believe command line parameters aren't wrapped in quotes and/or why it suddenly is a problem.  I also recently upgraded from GtkD 2.3.1 to 3.1.3 but I also don't think that has anything to do with it.  I'm using dub 0.9.23.

Here is my (shortened) output from dub --arch=x86_64 --verbose
....
Target 'C:\Projects\D Sandbox\.dub\build\application-debug-windows-x86_64-dmd_2067-3A2B5A93C6082612B74E2DA5D9309F80\dSandbox.exe' doesn't exist, need rebuild.
Building dsandbox ~master configuration "application", build type debug.
Compiling using dmd...
dmd -m64 -m64 -m64 -m64 -m64 -m64 -m64 -m64 -m64 -m64 -c -of.dub\build\application-debug-windows-x86_64-dmd_2067-3A2B5A93C6082612B74E2DA5D9309F80\dSandbox.obj -debug -g -w -version=Have_dsandbox -version=Have_gtk_d -version=Have_gtk_d_gtkdgl -version=Have_gtk_d_gtkd -version=Have_gtk_d_sv -version=Have_gtk_d_vte -version=Have_gtk_d_gstreamer -Isource -I..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\srcgl -I..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\src -I..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\srcsv -I..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\srcvte -I..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\srcgstreamer source\gtkhelloworld.d source\main.d
Linking...
dmd -of.dub\build\application-debug-windows-x86_64-dmd_2067-3A2B5A93C6082612B74E2DA5D9309F80\dSandbox.exe .dub\build\application-debug-windows-x86_64-dmd_2067-3A2B5A93C6082612B74E2DA5D9309F80\dSandbox.obj ..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\gtkdgl-3.lib ..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\gtkdsv-3.lib ..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\vted-3.lib ..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\gstreamerd-3.lib ..\..\Users\Doug Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\gtkd-3.lib -m64 -m64 -m64 -m64 -m64 -m64 -m64 -m64 -m64 -m64 -g
Error: cannot read file ..\..\Users\Doug.d
FAIL .dub\build\application-debug-windows-x86_64-dmd_2067-3A2B5A93C6082612B74E2DA5D9309F80\ dSandbox executable
Error executing command run:
dmd failed with exit code 1.

Note: the first invocation of dmd appears to succeed, but when I put that command verbatim into a Windows terminal I get "Error: cannot read file Nickerson\AppData\Roaming\dub\packages\gtk-d-3.1.3\srcgl.d" which of course is the second part (space separated) of the first -I option.

After wrapping the -I in quotes like so: -I"..\..\Users\......" -I"..\..\Users\...." it succeeds and I see the *.obj file in the .dub/build/application...../ directory.  That directory is created but empty when I ran dub build.

So, this makes me wonder:
1) Why the error on first invocation of dmd does not appear (-verbose or not) and halt dub?
     a) should dub maybe also check that indeed a *.obj file was produced before continuing?
2) Maybe the problem in the second invocation of dmd is a result of the missing *.obj (but it seems to again be a space in path issue)
3) Unrelated, but I think 10 "-m64" is a little excessive - not sure what is causing that although dmd doesn't seem to be affected.
4) is the -verbose output simply not showing the " that get inserted (or are supposed to) when dub does the actual dmd call?

**Comment by s-ludwig** [comment]
Already fixed as part of #540.
