### ISSUE TITLE
What does `dub add-path` do?

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#579]
I never used this command and don't understand why it's there.
The help says `Adds a default package search path.`, but I still don't understand.

- does it search for a single package in that path? ie. similar to add-local
- does it search for several dub.json in subdirectories?
- in this case is it similar to several add-local calls?
- where is the list of added paths, if any? What are the defaults?
- if it register packages like add-local, with which version?

**Comment by s-ludwig** [comment]
I've added a proper description on the help page for both, add-local and add-path now. You can get the list of all locally registered packages (add-local and add-path) using `dub list`. The list of registrations itself is stored in `~/.dub/packages/local-packages.json` (or `%APPDATA%/dub/packages/local-packages.json` on Windows).

**Comment by p0nce** [comment]
OK the help pages are perfect now.
There is a unbalanced parenthesis in the add-local help.

```
The version of the package is either determined automatically (see the
"add-path" command, or can be explicitly overwritten by passing a version on
the command line.
```

**Comment by jibal** [comment]
> I've added a proper description on the help page for both, add-local and add-path now. You can get the list of all locally registered packages (add-local and add-path) using `dub list`. The list of registrations itself is stored in `~/.dub/packages/local-packages.json` (or `%APPDATA%/dub/packages/local-packages.json` on Windows).

It's not a proper description when that information isn't on the page ... this is the only place I've seen that info.
It's also not a proper description when the format isn't described anywhere, or what `dub add-path` actually does ... and `dub add-path` itself is silent about what it did. Now that I know where the file is, I've observed that `dub add-path` overwrites it every time, rather than adding anything. And `dub list` does not mention its contents, and `dub build` doesn't mention it when listing the import paths; AFAICT, dub add-package has no effect at all (on my Windows 10 system). 

The description says "All direct sub folders of this path will be searched for package descriptions and will be made available as packages." ... searched how? Searched for what? What counts as a package description? Do you mean `package.d` files? Or `dub.{sdl,json}` recipe files? And given the prescribed directory layout of packagename/semver/packagename (which seems pointlessly redundant), neither `package.d` files nor recipe files will be found in direct subfolders.


The description of `dub add-local` is also not "proper".  None of the commands at https://dub.pm/cli-reference/dub/ list their arguments. And `dub add-local --help` says `dub add-local <path> [<version>] [<options...>]` but there is no description of those arguments. What path? At least when I run `dub add-local` it tells me "expected one of dub.json/dub.sdl/package.json" ... so what's the point of specifying a semver when it's part of the path? And if there's a comma missing from `dub.json` it doesn't tell me where, but produces a silly message about "non-conventional features that are deprecated  Warning This is most likely due to duplicated keys" (most likely, really?) and then crashes with a dub.internal.dyaml.parser.ParserException ... quality software there.

So I fixed the comma and ran `dub add-local` again and it said it registered my package ... I have no idea where how ... the `dub.json` for my project didn't change, and `dub build` still tells me that it can't find my local library. The only way I've found to use it is to manually add the dependency to my dub.json file.

I grew up with Bell Labs UNIX ... those people really knew how to write documentation, and the tradition has continued with opengroup, linux, and other documentation descended from the original UNIX. It's not that hard to be precise and complete if you try.
