### ISSUE TITLE
Specifying A Library Version With ~> Doesn't Work On Mac

### ISSUE THREAD

**Issue by JackStouffer** [D-Programming-Language/dub#583]
I have the following dub.json file
```
{
    "name": "dungeon",
    "sourcePaths": ["."],
    "dependencies": {
        "dgame": "~>0.6.0-beta.1"
    },
    "targetType": "executable"
}
```
This file successfully downloads dgame on Windows and Ubuntu, but on Mac I get the following error:
```
$ dub upgrade
Upgrading project in /Users/Jack/Dropbox/code/dlang/dungeon_game
Error executing command upgrade:
Root package dungeon contains reference to invalid package dgame
```
But, this dub.json file works just fine
```
{
    "name": "dungeon",
    "sourcePaths": ["."],
    "dependencies": {
        "dgame": ">=0.5.0"
    },
    "targetType": "executable"
}
```
Using: DUB version 0.9.23, built on Apr  6 2015

**Comment by s-ludwig** [comment]
There must be something wrong with your local package cache (`~/.dub/packages`), everything works fine for me on either 0.9.23 or master. Can you post the output of `dub upgrade --vverbose`? After that I'd try to run `dub clean-caches` to see if the metadata is the issue, or run `rm -r ~/.dub/packages` if that didn't help. If possible, please make a quick copy of the .dub directory before all that, so that it's possible to find the root cause if the log output doesn't help.
