### ISSUE TITLE
OS-dependent import library does not work with --combined

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#697]
**Summary**

It doesn't seem possible to have a library link only on linux and then build with `--combined` on another OS.

**OS:** Windows, OSX

**How to reproduce**

Try this `dub.json`

```json
{
    "name": "test",

    "dependencies":
    {
        "x11": "==1.0.8"
    }
}
```
Note that the x11 `dub.json` uses `libs-linux` to link the X11 import library only on Linux. 
https://github.com/nomad-software/x11/blob/master/package.json#L14

Contents of `source/app.d` (unimportant)
```
void main(string[]args)
{
}
```

**When built without --combined** 
`dub -f -v` => works

**When built with --combined** 
`dub -f -v --combined` => link error
```
Undefined symbols for architecture x86_64:
  "_XrmQuarkToString", referenced from:
      _XrmNameToString in test.o
      _XrmClassToString in test.o
      _XrmRepresentationToString in test.o
  "_XrmStringToQuark", referenced from:
      _XrmStringToName in test.o
      _XrmStringToClass in test.o
      _XrmStringToRepresentation in test.o
      _XStringToContext in test.o
  "_XrmStringToQuarkList", referenced from:
      _XrmStringToNameList in test.o
      _XrmStringToClassList in test.o
  "__XData32", referenced from:
      _Data32 in test.o
  "__XDeqAsyncHandler", referenced from:
      _DeqAsyncHandler in test.o
  "__XFlushGCCache", referenced from:
      _FlushGC in test.o
  "__XRead", referenced from:
      __XRead16 in test.o
     (maybe you meant: __XRead16, __XRead16Pad )
  "__XReadPad", referenced from:
      __XRead16Pad in test.o
  "__XSend", referenced from:
      _Data in test.o
ld: symbol(s) not found for architecture x86_64
```

I don't really get why the linker asks for those symbols.
This particular example was on Mac but something equivalent  also happens on Windows.

**Comment by s-ludwig** [comment]
This seems to be not a DUB issue, my guess is the following: The X11 package contains some non-template helper functions that call imported functions (e.g. `x11.Xlibint.Data` calls `_XSend`). When the package is compiled as an individual static library, the linker will pick only the functions that are actually used by the executable, dopping things like `x11.Xlibint.Data`. However, it doesn't do the same for the executable itself, so that when the package is compiled together with the executable's source code, these helpers end up in the final executable.

Two ways to fix this:
 - Create an "x11" configuration in the executable package that has a `platforms "linux"` field and only add the "x11" dependency there.
 - Change all helper functions in the x11 package to be template functions (with empty template parameter list).
