### ISSUE TITLE
SDL subConfiguration vs JSON subConfigurations

### ISSUE THREAD

**Issue by Geod24** [D-Programming-Language/dub#721]
In JSON, the way to specify alternative configuration is by the `subConfigurations` object. In SDL, that field is named `subConfiguration`. Is the inconsistency voluntary ?
Also, the documentation of the site (http://code.dlang.org/package-format?lang=sdl#configurations) is incorrect:

```
	dependency "somepackage" version=">=1.0.0"
	"subConfiguration" "somepackage" "glut-app"
```

This gave me an awfully helpful error message:
```
/mnt/shared/projects/vibed/vibe.d/tests/unixsockets/dub.sdl(2): Error: Anonymous tags are not allowed at the root level.
```

So removing the `"` was the way to go.

**Comment by s-ludwig** [comment]
There are some more of these, for example `"dependencies"` (JSON) vs. `dependency` (SDL) or `"subPackages"` vs. `subPackage`. They are indeed deliberately converted to singular form, because that's what they do - they only operate on single entities, while the JSON counterpart, due to the limitations of the format has to group several entities to achieve an efficient representation.

I'll fix the documentation mistake.
