### ISSUE TITLE
Store in cache the last config and the last buildType

### ISSUE THREAD

**Issue by BBasile** [D-Programming-Language/dub#753]
DUB could generate a cache file that indicates which are the last config and buildType. This could be used by the IDEs when they open a package to automatically select a config in their GUI.

The two properties could be stored in dub.json file that's generated in the hidden .dub folder of each package.

example:
```JSON
{
	"dub": {
        "lastConfig": "configIdentifier",
        "lastBuildType": "buildTypeIdentifier",
		"lastUpgrade": "2016-01-24T04:40:08.962895",
		"cachedUpgrades": {}
	}
}
```

**Comment by BBasile** [comment]
These information are in the `BuildCommand` class (`string m_buildType` and `string m_buildConfig`) but they seem to be expanded to a specific set of parameter later, for example in the `Project` class, there is no way to store which were the last buildType and config.

Is this feature implementable ?

**Comment by s-ludwig** [comment]
That would require `Project.m_packageConfig` to be exposed to the `Dub` class in some way, so that `Dub.generateProject` can write the fields in question, but it would certainly be an option. One question is if going this route is in general sufficient to avoid a per-IDE meta data file (i.e. there are still things like window layout, opened files, debugger settings etc.).

**Comment by BBasile** [comment]
No it's not sufficient for sure. But the two settings I was talking about are a DUB thing. 

Anyway, after a quick look at the sources I've closed the issue because I cannot do it easily myself and since nobody seemed interested (among the small number of people involved in D IDEs) last 28 days I think we can forget this feature request.
