### ISSUE TITLE
$<name>_PACKAGE_DIR doesn't work with hyphen in package name

### ISSUE THREAD

**Issue by John-Colvin** [D-Programming-Language/dub#774]
e.g. with `derelict-cl`

**Comment by s-ludwig** [comment]
You need to use `derelict_cl_PACKAGE_DIR`. Dashes are converted to underscores (see https://github.com/D-Programming-Language/dub/blob/667608db9ea059fd61102109202179a65c5eef20/source/dub/project.d#L1199). This isn't ideal due to the ambiguity it creates, but the same conversion happens (and needs to happen) in other places as well, for example `-version=Have_derelict_cl`.

**Comment by John-Colvin** [comment]
Ah, ok. How about this: https://github.com/D-Programming-Language/dub-registry/pull/135

**Comment by John-Colvin** [comment]
I'm still getting `Invalid variable: derelict_cl_PACKAGE_DIR`

**Comment by s-ludwig** [comment]
Oh, it's also converted to upper case, I missed that, too. I'll add that on top of #135.

**Comment by s-ludwig** [comment]
Ok, I've verified that `$DERELICT_CL_PACKAGE_DIR` does indeed work.

**Comment by John-Colvin** [comment]
Thanks :)
